azs:
- name: z1
  cloud_properties: {zone: europe-west2-a}
- name: z2
  cloud_properties: {zone: europe-west2-b}
- name: z3
  cloud_properties: {zone: europe-west2-c}
- name: z4
  cloud_properties: {zone: europe-west1-b}
- name: z5
  cloud_properties: {zone: europe-west1-c}
- name: z6
  cloud_properties: {zone: europe-west1-d}


vm_types:
- name: sharedcpu
  cloud_properties:
    machine_type: g1-small
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
    service_scopes:
    - compute.readonly
    - devstorage.read_write
    - logging.write
    - monitoring.write
    preemptible: true

- name: minimal
  cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 20
    root_disk_type: pd-ssd
    service_scopes:
    - compute.readonly
    - devstorage.read_write
    - logging.write
    - monitoring.write
    preemptible: true

- name: small
  cloud_properties:
    machine_type: n1-standard-2
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
    service_scopes:
    - compute.readonly
    - devstorage.read_write
    - logging.write
    - monitoring.write
    preemptible: true

- name: medium
  cloud_properties:
    machine_type: n1-standard-8
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
    service_scopes:
    - compute.readonly
    - devstorage.read_write
    - logging.write
    - monitoring.write
    preemptible: true

- name: small-highmem
  cloud_properties:
    machine_type: n1-highmem-2
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
    service_scopes:
    - compute.readonly
    - devstorage.read_write
    - logging.write
    - monitoring.write
    preemptible: true

- name: compilation
  cloud_properties:
    machine_type: n1-highcpu-4
    root_disk_size_gb: 50
    root_disk_type: pd-ssd
    service_scopes:
    - compute.readonly
    - devstorage.read_write
    preemptible: true

vm_extensions:
- name: 1GB_ephemeral_disk
  cloud_properties:
    root_disk_size_gb: 1
    root_disk_type: pd-ssd
- name: 5GB_ephemeral_disk
  cloud_properties:
    root_disk_size_gb: 5
    root_disk_type: pd-ssd
- name: 10GB_ephemeral_disk
  cloud_properties:
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
- name: 50GB_ephemeral_disk
  cloud_properties:
    root_disk_size_gb: 50
    root_disk_type: pd-ssd
- name: 100GB_ephemeral_disk
  cloud_properties:
    root_disk_size_gb: 100
    root_disk_type: pd-ssd
- name: 500GB_ephemeral_disk
  cloud_properties:
    root_disk_size_gb: 500
    root_disk_type: pd-ssd
- name: 1TB_ephemeral_disk
  cloud_properties:
    root_disk_size_gb: 1000
    root_disk_type: pd-ssd
- name: ssh-proxy-and-router-lb
  cloud_properties:
    ephemeral_external_ip: true
    ports:
    - host: 80
    - host: 443
    - host: 2222
- name: cf-router-network-properties
  cloud_properties:
    backend_service: cf-lb-backend-service
    ephemeral_external_ip: true
    ports:
    - host: 1024-1123
- name: cf-tcp-router-network-properties
- name: internet-required
  cloud_properties:
    ephemeral_external_ip: true
- name: internet-not-required
  cloud_properties:
    ephemeral_external_ip: false
- name: diego-ssh-proxy-network-properties
- name: jenkins-pool
  cloud_properties:
    ephemeral_external_ip: true
    backend_service: buildtools-backend-service
- name: mysql-pool
  cloud_properties:
    ephemeral_external_ip: false
    backend_service:
      name: mysql-backend-service
      scheme: INTERNAL

disk_types:
- name: 1GB
  disk_size: 1_024
  cloud_properties:
    type: pd-ssd
    encrypted: true
- name: 5GB
  disk_size: 5_120
  cloud_properties:
    type: pd-ssd
    encrypted: true
- name: 10GB
  disk_size: 10_240
  cloud_properties:
    type: pd-ssd
    encrypted: true
- name: 100GB
  disk_size: 100_240
  cloud_properties:
    type: pd-ssd
    encrypted: true

networks:
- name: default
  type: manual
  subnets:
  - range: 192.168.0.0/16
    gateway: 192.168.0.1
    azs:
    - z1
    - z2
    - z3
    dns: [8.8.8.8, 8.8.4.4]
    cloud_properties:
      ephemeral_external_ip: false
      network_name: bosh
      subnetwork_name: cf-private-europe-west2
      tags: [internal, cf-internal, no-ip]
- name: compilation
  type: manual
  subnets:
  - range: 10.200.0.0/24
    gateway: 10.200.0.1
    azs:
    - z4
    - z5
    - z6
    dns: [8.8.8.8, 8.8.4.4]
    cloud_properties:
      ephemeral_external_ip: false
      network_name: bosh
      subnetwork_name: cf-compilation-europe-west2
      tags: [internal, cf-internal, no-ip]
- name: services
  type: manual
  subnets:
  - range: 10.30.0.0/24
    gateway: 10.30.0.1
    azs:
    - z1
    - z2
    - z3
    dns: [8.8.8.8, 8.8.4.4]
    cloud_properties:
      ephemeral_external_ip: false
      network_name: bosh
      subnetwork_name: cf-services-europe-west2
      tags: [cf-internal, no-ip]
- name: buildstack
  type: manual
  subnets:
  - range: 10.40.0.0/24
    gateway: 10.40.0.1
    reserved: [10.40.0.2]
    azs:
    - z1
    - z2
    - z3
    dns: [8.8.8.8, 8.8.4.4]
    cloud_properties:
      ephemeral_external_ip: false
      network_name: bosh
      subnetwork_name: buildstack-europe-west2
      tags: [cf-internal, no-ip]

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: compilation
  network: compilation

