azs:
- name: z1
  cloud_properties: {zone: europe-west2-a}
- name: z2
  cloud_properties: {zone: europe-west2-b}
- name: z3
  cloud_properties: {zone: europe-west2-c}

vm_types:
- name: t2.small
  cloud_properties:
    machine_type: g1-small
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
    service_scopes:
    - compute.readonly
    - devstorage.read_write
    preemptible: true
- name: m3.medium
  cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 20
    root_disk_type: pd-ssd
    service_scopes:
    - compute.readonly
    - devstorage.read_write
    preemptible: true
- name: m3.large
  cloud_properties:
    machine_type: n1-standard-2
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
    service_scopes:
    - compute.readonly
    - devstorage.read_write
    preemptible: true
- name: m3.xlarge
  cloud_properties:
    machine_type: n1-standard-4
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
    service_scopes:
    - compute.readonly
    - devstorage.read_write
    preemptible: true
- name: c3.large
  cloud_properties:
    machine_type: n1-highcpu-2
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
    service_scopes:
    - compute.readonly
    - devstorage.read_write
    preemptible: true
- name: r3.xlarge
  cloud_properties:
    machine_type: n1-standard-8
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
    service_scopes:
    - compute.readonly
    - devstorage.read_write
    preemptible: true
- name: r3.xlarge.highcpu
  cloud_properties:
    machine_type: n1-highcpu-32
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
    service_scopes:
    - compute.readonly
    - devstorage.read_write
    preemptible: true
- name: sharedcpu
  cloud_properties:
    machine_type: g1-small
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
    service_scopes:
    - compute.readonly
    - devstorage.read_write
    preemptible: true
- name: minimal
  cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 20
    root_disk_type: pd-ssd
    service_scopes:
    - compute.readonly
    - devstorage.read_write
    preemptible: true
- name: small
  cloud_properties:
    machine_type: n1-standard-2
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
    service_scopes:
    - compute.readonly
    - devstorage.read_write
    preemptible: true
- name: medium
  cloud_properties:
    machine_type: n1-standard-8
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
    service_scopes:
    - compute.readonly
    - devstorage.read_write
    preemptible: true
- name: small-highmem
  cloud_properties:
    machine_type: n1-highmem-2
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
    service_scopes:
    - compute.readonly
    - devstorage.read_write
    preemptible: true
- name: compilation
  cloud_properties:
    machine_type: n1-highcpu-4
    root_disk_size_gb: 50
    root_disk_type: pd-ssd
    service_scopes:
    - compute.readonly
    - devstorage.read_write
    preemptible: true

vm_extensions:
- name: 1GB_ephemeral_disk
  cloud_properties:
    root_disk_size_gb: 1
    root_disk_type: pd-ssd
- name: 5GB_ephemeral_disk
  cloud_properties:
    root_disk_size_gb: 5
    root_disk_type: pd-ssd
- name: 10GB_ephemeral_disk
  cloud_properties:
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
- name: 50GB_ephemeral_disk
  cloud_properties:
    root_disk_size_gb: 50
    root_disk_type: pd-ssd
- name: 100GB_ephemeral_disk
  cloud_properties:
    root_disk_size_gb: 100
    root_disk_type: pd-ssd
- name: 500GB_ephemeral_disk
  cloud_properties:
    root_disk_size_gb: 500
    root_disk_type: pd-ssd
- name: 1TB_ephemeral_disk
  cloud_properties:
    root_disk_size_gb: 1000
    root_disk_type: pd-ssd
- name: ssh-proxy-and-router-lb
  cloud_properties:
    ephemeral_external_ip: true
    ports:
    - host: 80
    - host: 443
    - host: 2222
- name: cf-router-network-properties
  cloud_properties:
    backend_service: cf-lb-backend-service
    ephemeral_external_ip: true
    ports:
    - host: 1024-1123
- name: cf-tcp-router-network-properties
- name: internet-required
  cloud_properties:
    ephemeral_external_ip: true
- name: internet-not-required
  cloud_properties:
     ephemeral_external_ip: false
- name: diego-ssh-proxy-network-properties

disk_types:
- name: 1GB
  disk_size: 1_024
  cloud_properties:
    type: pd-ssd
    encrypted: true
- name: 5GB
  disk_size: 5_120
  cloud_properties:
    type: pd-ssd
    encrypted: true
- name: 10GB
  disk_size: 10_240
  cloud_properties:
    type: pd-ssd
    encrypted: true
- name: 100GB
  disk_size: 100_240
  cloud_properties:
    type: pd-ssd
    encrypted: true

networks:
- name: compilation
  type: manual
  subnets:
  - range: 10.0.0.0/26
    gateway: 10.0.0.1
    reserved: [10.0.0.2-10.0.0.6]    
    azs:
    - z1
    dns: [8.8.8.8, 8.8.4.4]
    cloud_properties:
      ephemeral_external_ip: false
      network_name: bosh
      subnetwork_name: control-europe-west2
      tags: [cf-internal, no-ip]
- name: default
  type: manual
  subnets:
  - range: 10.10.0.0/22
    gateway: 10.10.0.1
    azs:
    - z1
    - z2
    - z3
    dns: [8.8.8.8, 8.8.4.4]
    cloud_properties:
      ephemeral_external_ip: true
      network_name: bosh
      subnetwork_name: ert-europe-west2

compilation:
  workers: 6
  reuse_compilation_vms: true
  az: z1
  vm_type: compilation
  network: compilation

