releases:
- {name: stackdriver-tools, version: 1.0.6}

addons:
  - name: stackdriver
    jobs:
    - name: google-fluentd
      release: stackdriver-tools
    - name: stackdriver-agent
      release: stackdriver-tools
    include:
      deployments: [bosh-haraka]
